'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("inoVBATools.ResourceLang", GetType(ResourceLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCancel() As String
            Get
                Return ResourceManager.GetString("BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnClose() As String
            Get
                Return ResourceManager.GetString("BtnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnCopy() As String
            Get
                Return ResourceManager.GetString("BtnCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnInsert() As String
            Get
                Return ResourceManager.GetString("BtnInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnOK() As String
            Get
                Return ResourceManager.GetString("BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSave() As String
            Get
                Return ResourceManager.GetString("BtnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Switch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BtnSwitch() As String
            Get
                Return ResourceManager.GetString("BtnSwitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copyright ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoCopyright() As String
            Get
                Return ResourceManager.GetString("InfoCopyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoTitle() As String
            Get
                Return ResourceManager.GetString("InfoTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoVersion() As String
            Get
                Return ResourceManager.GetString("InfoVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ArrangeI icons ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainArrangeIcons() As String
            Get
                Return ResourceManager.GetString("MainArrangeIcons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cascade ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainCascade() As String
            Get
                Return ResourceManager.GetString("MainCascade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close all ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainCloseAll() As String
            Get
                Return ResourceManager.GetString("MainCloseAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainFile() As String
            Get
                Return ResourceManager.GetString("MainFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainHelp() As String
            Get
                Return ResourceManager.GetString("MainHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainInfo() As String
            Get
                Return ResourceManager.GetString("MainInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New window ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainNewWindow() As String
            Get
                Return ResourceManager.GetString("MainNewWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainQuit() As String
            Get
                Return ResourceManager.GetString("MainQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainSettings() As String
            Get
                Return ResourceManager.GetString("MainSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatus() As String
            Get
                Return ResourceManager.GetString("MainStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tile horizontal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTileHorizontal() As String
            Get
                Return ResourceManager.GetString("MainTileHorizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tile vertical ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTileVertical() As String
            Get
                Return ResourceManager.GetString("MainTileVertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTools() As String
            Get
                Return ResourceManager.GetString("MainTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindows() As String
            Get
                Return ResourceManager.GetString("MainWindows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgHint() As String
            Get
                Return ResourceManager.GetString("MsgHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsLanguage() As String
            Get
                Return ResourceManager.GetString("SettingsLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The application needs as restart to apply the language settings. Do you want to restart? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsRestart() As String
            Get
                Return ResourceManager.GetString("SettingsRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsTitle() As String
            Get
                Return ResourceManager.GetString("SettingsTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
